settings:
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  model_path: /raid/s3/opengptx/mfrey/3.73T-Tokens/eid_2025-04-29__13-48-21_fed2a6d3-model-seen_steps_445500-seen_tokens_3737124864000-target_steps_447337-target_tokens_3752534736896.bin
  device: 7
  sequence_length: 1024
  step_profile:
    gradient_accumulation_steps: 1
    local_train_micro_batch_size: 2
    sequence_length: 8192

text_inference_component:
  component_key: inference_component
  variant_key: text
  config:
    device: ${settings.device}
    model:
      instance_key: checkpointed_model
      pass_type: BY_REFERENCE
    tokenizer:
      component_key: tokenizer
      variant_key: pretrained_sp_tokenizer
      config:
        tokenizer_model_file: /raid/s3/opengptx/mfrey/3.73T-Tokens/tokenizer/eurolingua_tokenizer.model
    sequence_length: ${settings.sequence_length}
    eod_token: <|endoftext|>
    prompt_template: "{prompt_input}" # "<instruction> Du bist Moody, ein LLM welches Menschen helfen soll. user: {prompt_input}"

    system_prompt_path: "/home/markus_frey/Github/modalities/tutorials/instruct_teuken/configs/system_prompt.txt"
    chat_template: "System:\n{system_prompt}\nUser:{user_prompt}\nAssistant:\n"

    temperature: 1
    # chat: false

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

checkpointed_model:
  component_key: model
  variant_key: fsdp1_checkpointed
  config: 
    checkpoint_loading:
      component_key: checkpoint_loading
      variant_key: torch
      config:
        device: ${settings.device}
        precision: BF16
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.model_path}

model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: gpt2
        weight_init_type: scaled
        mean: 0.0
        std: 0.02
        num_layers: ${model_raw.config.n_layer}
model_raw:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.step_profile.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: 250880
    n_layer: 32
    n_head_q: 32
    n_head_kv: 8
    ffn_hidden: 21248
    n_embd: 4096
    dropout: 0.0
    bias: false
    attention_config:
      qkv_transforms:
      - type_hint: RotaryTransform
        config:
          n_embd: ${model_raw.config.n_embd}
          n_head: ${model_raw.config.n_head_q}
          seq_length_dim: -2
          base_freq: 500000
    attention_implementation: pytorch_flash
    activation_type: swiglu
    attention_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    ffn_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    lm_head_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    use_weight_tying: false