settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpoint_saving_path: /raid/s3/opengptx/mfrey/fineweb-30B/checkpoints
  intervals:
    training_log_interval_in_steps: 100
    checkpointing_interval_in_steps: 10000
    evaluation_interval_in_steps: 1000
  consistency_enforcement:
    enforce_tokens_per_step_consistency: true
    enforce_last_step_logged: false
    enforce_last_step_evaluated: false
    enforce_last_step_checkpointed: false
  step_profile: 
    gradient_accumulation_steps: 6
    local_train_micro_batch_size: 3
    sequence_length: 2048
  warmstart_checkpoint_paths:
    model_checkpoint_path: "/raid/s3/opengptx/mfrey/fineweb-30B/checkpoints/2025-08-07__17-50-58_89893f7f/eid_2025-08-07__17-50-58_89893f7f-model-seen_steps_30000-seen_tokens_4608000000-target_steps_39508-target_tokens_6068428800.bin"
    optimizer_checkpoint_path: "/raid/s3/opengptx/mfrey/fineweb-30B/checkpoints/2025-08-07__17-50-58_89893f7f/eid_2025-08-07__17-50-58_89893f7f-optimizer-seen_steps_30000-seen_tokens_4608000000-target_steps_39508-target_tokens_6068428800.bin"
  training_target:
    num_target_tokens: 9031680000 # 9216000000 #9031680000 #
    num_target_steps: 60000
  training_progress:
    global_num_seen_tokens: 4608000000
    num_seen_steps: 30000
    num_seen_samples: 0
    last_step: 29999

collate_fn:
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: combined
  config:
    datasets:
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/deu_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/eng_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/fra_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/ita_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/spa_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/nob_Latn_train.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    dataloader_tag: train
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.step_profile.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: resumable_distributed_sampler
          config:
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: true
            seed: 42
            drop_last: true
            skip_num_global_samples: ${settings.training_progress.num_seen_samples}
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataset:
  component_key: dataset
  variant_key: combined
  config:
    datasets:
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/deu_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/eng_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/fra_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/ita_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/spa_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}
      - component_key: dataset
        variant_key: packed_mem_map_dataset_continuous
        config:
          raw_data_path: /raid/s3/opengptx/mfrey/fineweb-30B/packed/nob_Latn_val.pbin
          sequence_length: ${settings.step_profile.sequence_length}
          sample_key: ${settings.referencing_keys.sample_key}

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    dataloader_tag: val
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.step_profile.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            drop_last: true
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_loading:
  component_key: checkpoint_loading
  variant_key: fsdp1
  config:
    global_rank: ${settings.cuda_env.global_rank}
    block_names: [GPT2Block]
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1   # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp1
      config:
        checkpoint_path: ${settings.paths.checkpoint_saving_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

app_state:
  component_key: app_state
  variant_key: raw
  config:
    model: 
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    lr_scheduler:
      instance_key: lr_scheduler
      pass_type: BY_REFERENCE

wrapped_model:
  component_key: model
  variant_key: fsdp1_checkpointed
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    checkpoint_loading:
      instance_key: checkpoint_loading
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.warmstart_checkpoint_paths.model_checkpoint_path}

model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: gpt2
        weight_init_type: scaled
        mean: 0.0
        std: 0.02
        num_layers: ${model_raw.config.n_layer}

model_raw:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.step_profile.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: 251008 
    n_layer: 24
    n_head_q: 32
    n_head_kv: 8
    ffn_hidden: 8192
    n_embd: 2048
    dropout: 0.0
    bias: false
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform
          config:
            n_embd: ${model_raw.config.n_embd}
            n_head: ${model_raw.config.n_head_q}
            seq_length_dim: -2
            base_freq: 10000
    attention_implementation: manual
    activation_type: swiglu
    attention_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    ffn_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    lm_head_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    use_weight_tying: true

# ---
lr_scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 1.0e-4
    div_factor: 10
    final_div_factor: 10
    total_steps: 30000
    pct_start: 0.05
    anneal_strategy: cos
    last_epoch: -1
# ---
optimizer:
  component_key: optimizer
  variant_key: fsdp1_checkpointed
  config:
    optimizer:
      instance_key: optimizer_original
      pass_type: BY_REFERENCE
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    checkpoint_loading:
      instance_key: checkpoint_loading
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.warmstart_checkpoint_paths.optimizer_checkpoint_path}

optimizer_original:  
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    weight_decay_groups_excluded: [embedding, layernorm]
    wrapped_model: 
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

# optimizer:
#   component_key: optimizer
#   variant_key: adam_w
#   config:
#     lr: 0.0001
#     betas: [0.9, 0.95]
#     eps: 1e-8
#     weight_decay: 1e-1
#     weight_decay_groups_excluded: [embedding, layernorm]
#     wrapped_model: 
#       instance_key: wrapped_model
#       pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp1
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    global_rank: ${settings.cuda_env.global_rank}
    num_seen_steps: ${settings.training_progress.num_seen_steps}
    num_target_steps: ${settings.training_target.num_target_steps}
    train_dataloader_tag: ${train_dataloader.config.dataloader_tag}
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    global_rank: ${settings.cuda_env.global_rank}
    project: 2b_config
    mode: ONLINE
    experiment_id: ${settings.experiment_id}
    directory: data/wandb_storage
    config_file_path: ${settings.config_file_path}